services:
  nmap:
    image: instrumentisto/nmap:latest
    entrypoint: nmap
    volumes:
      - ./output:/output

  subfinder:
    image: projectdiscovery/subfinder:latest
    entrypoint: subfinder
    volumes:
      - ./output:/output

  httpx:
    image: projectdiscovery/httpx:latest
    entrypoint: httpx
    volumes:
      - ./output:/output

  feroxbuster:
    image: epi052/feroxbuster:latest
    entrypoint: feroxbuster
    volumes:
      - ./output:/output
      - ./wordlists:/wordlists

  katana:
    image: projectdiscovery/katana:latest
    entrypoint: katana
    network_mode: host
    volumes:
      - ./output:/output

  wpscan:
    image: wpscanteam/wpscan:latest
    volumes:
      - ./output:/output

  nuclei:
    image: projectdiscovery/nuclei:latest
    entrypoint: nuclei
    volumes:
      - ./output:/output
